name = "glox"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
format = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
clip = ">= 1.1.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
geckolex = { git = "https://www.github.com/mewfinity06/geckolex", ref = "master" }
in = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
